# Generated by Django 4.1.5 on 2023-01-28 17:18

from django.db import migrations


def populate_roles(apps, schema_editor):
    Role = apps.get_model('login', 'Role')
    Role.objects.create(name='admin', description='Admin', is_staff=True)
    Role.objects.create(name='staff', description='Staff', is_staff=True)
    Role.objects.create(name='member', description='Member', is_staff=False)


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_role_is_staff'),
    ]

    operations = [
        migrations.RunPython(populate_roles),
    ]
