# Generated by Django 4.1.5 on 2023-01-26 03:04

from django.db import migrations


# populating the database with some brands


def populate_brands(apps, schema_editor):
    Brand = apps.get_model('shoes', 'Brand')
    Brand.objects.create(
        name='nike', image='https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Logo_NIKE.svg/1200px-Logo_NIKE.svg.png')
    Brand.objects.create(
        name='adidas', image='https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Adidas_Logo.svg/2560px-Adidas_Logo.svg.png')
    Brand.objects.create(
        name='puma', image='https://seeklogo.com/images/P/puma-se-logo-ACC0F72575-seeklogo.com.png')
    Brand.objects.create(
        name='reebok', image='https://preview.thenewsmarket.com/Previews/RBOK/StillAssets/1920x1080/551064.png')
    Brand.objects.create(
        name='vans', image='https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Vans-logo.svg/2560px-Vans-logo.svg.png')


def populate_shoe_types(apps, schema_editor):
    ShoeType = apps.get_model('shoes', 'ShoeType')
    ShoeType.objects.create(style='sneaker')
    ShoeType.objects.create(style='boot')
    ShoeType.objects.create(style='sandal')
    ShoeType.objects.create(style='dress')
    ShoeType.objects.create(style='other')


def populate_shoe_gender(apps, schema_editor):
    ShoeGender = apps.get_model('shoes', 'ShoeGender')
    ShoeGender.objects.create(name='men')
    ShoeGender.objects.create(name='women')


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0002_shoegender_shoe_gender'),
    ]

    operations = [
        migrations.RunPython(populate_brands),
        migrations.RunPython(populate_shoe_types),
        migrations.RunPython(populate_shoe_gender),
    ]
