# Generated by Django 4.1.5 on 2023-02-18 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0003_auto_20230125_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shoe',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
