# Generated by Django 4.1.5 on 2023-02-18 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0004_shoe_description_shoe_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoeMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='shoe',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoes.shoematerial'),
        ),
    ]
