# Generated by Django 4.1.5 on 2023-02-18 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0005_shoematerial_alter_shoe_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='image',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
