# Generated by Django 4.1.5 on 2023-02-04 17:39

from django.db import migrations

# populate the OrderType table with the following values:
# 1. Shipping
# 2. Pickup


def populate_order_types(apps, schema_editor):
    OrderType = apps.get_model('sales', 'OrderType')
    OrderType.objects.create(name='shipping')
    OrderType.objects.create(name='pickup')


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_order_types),
    ]
